config/routes.rb
Rails.application.routes.draw do
  
  resources :donations
  get 'donation/index'
  resources :reviews
  get 'homevd/index'

  get 'home/index'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'products/index'

  get 'payments/searchingName'

  post 'validate3',  :controller=>'payments', :action=>'results' 

  resources :foods

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

resources :payments, only: [:index, :new, :create]
  get 'payments/index'

  get 'payments/new'

  get 'payments/create'

  resources :needs
  resources :customersps do
      resources :foodsps
end

get '/fat' =>'fatintake#checkFatIntakeSP'
post '/validate1' =>'fatintake#isFatCal'

  resources :shakes
  resources :profiles
  resources :analytics
  resources :customers
  get 'home2/index'

  get 'home1/index'

  get 'home1/about'
  
  get '/graphs' =>'analytics#graphs'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  
  get '/proteinC' =>'analytics#proteinCalc'
  
  
  post '/validate', :controller=>'analytics', :action=>'proteinCounter'

  get 'home1/contactUs'

  get 'home1/findUs'

  devise_for :users

  root :to => 'home1#index'
  
  get 'home/index'
  

end

app/models/analytic.rb
class Analytic < ActiveRecord::Base
    
    validates :Food, :Day, :Protein, :Carbohydrates,:Fats, :Calories, :Country, presence: true
    
    validates :Protein,:Carbohydrates,:Fats,:Calories, format: { with: /\A[0-9]+\z/,
     message: "accepts digits only!" }
     
     
     validates_each :Food, :Day , :Country  do |record, attr, value|
record.errors.add(attr, 'must contain only letters!') if
value =~ /[^\A[a-zA-Z]+\z]/
end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/customersp.rb
class Customersp < ActiveRecord::Base
	has_many :foodsps

validates :namesp, :surnamesp, :emailsp, presence: true
# validate that the phone number only contains digits
# tests if the value of the phone matches
# the regular expression given via with:
validates :phonesp, format: { with: /\A[0-9]+\z/,
message: "accepts digits only!" }
# we have to add the error so that the record becomes invalid
# when the value of the attribute does not match the
# regular expression
validates_each :namesp, :surnamesp do |record, attr, value|
record.errors.add(attr, 'must contain only letters!') if
value =~ /[^\A[a-zA-Z]+\z]/
end


end

app/models/donation.rb
class Donation < ActiveRecord::Base
    
    has_many :orders
validates :firstname, :lastname, presence: true
end

app/models/foodsp.rb
class Foodsp < ActiveRecord::Base
  belongs_to :customersp


validates :productsp, presence: true

# validate that the nutients and price  only contains digits
# tests if the value of the phone matches
# the regular expression given via with:
validates :pricesp, :caloriessp, :proteinssp, :sugarsp,:fatsp,  format: { with: /\A[0-9]+\z/,
message: "accepts digits only!" }

# we have to add the error so that the record becomes invalid
# when the value of the attribute does not match the
# regular expression
validates_each :productsp do |record, attr, value|
record.errors.add(attr, 'must contain only letters!') if
value =~ /[^\A[a-zA-Z]+\z]/
end


end

app/models/need.rb
class Need < ActiveRecord::Base

validates :firstname, :description, presence: true

validates :lastname, :manufacturer, :color, format: { with: /\A[0-9]+\z/,
message: "accepts digits only!" }


validates_each :firstname, :description do |record, attr, value|
record.errors.add(attr, 'must contain only letters!') if
value =~ /[^\A[a-zA-Z]+\z]/
end

end

app/models/need_observer.rb
#saved in the file app/models/need_observer.rb
require 'sp_logger'
class NeedObserver < ActiveRecord::Observer
def after_update(record)
# use the SyLogger instance method to retrieve the single instance/object of the class
@logger = SpLogger.instance
# use the logger to log/record a message about the updated car
@logger.logInformation("###############Observer Demo:#")
@logger.logInformation("+++ NeedObserver: The need of
#{record.firstname} #{record.lastname}
has been updated. cost #{record.cost}")
@logger.logInformation("##############################")
end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  require "active_merchant/billing/rails"

  attr_accessor :card_security_code
  attr_accessor :credit_card_number
  attr_accessor :expiration_month
  attr_accessor :expiration_year

has_many :orders
validates :first_name, :last_name, :card_security_code, :credit_card_number, :amount, presence: true


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :card_security_code, presence: true
  validates :credit_card_number, presence: true
  validates :expiration_month, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  validates :expiration_year, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  validate :valid_card

  def credit_card
    ActiveMerchant::Billing::CreditCard.new(
      number:              credit_card_number, #4545888888888888
      verification_value:  card_security_code, # 123
      month:               expiration_month, #1
      year:                expiration_year, #2020
      first_name:          first_name, #Vinayak
      last_name:           last_name, #Dhole
    )
  end

  def valid_card
  if credit_card.valid?
        errors.add(:base, "Credited Successfully")
      false
    else
      true
    end
end
  
  def process
    if !valid_card
      response = GATEWAY.authorize(amount * 100, credit_card)
      if response.success?
        transaction = GATEWAY.capture(amount * 100, response.authorization)
        if !transaction.success?
          errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
          false
        end
        update_columns({authorization_code: transaction.authorization, success: true})
        true
      else
        errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
        false
      
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
 
end

app/models/review.rb
class Review < ActiveRecord::Base
has_many :orders
validates :name, :email, :phone, :description, presence: true
end

app/models/shake.rb
class Shake < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
end

app/controllers/home2_controller.rb
class Home2Controller < ApplicationController
  def index
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/home2_helper.rb
module Home2Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/views/home2/index.html.erb
<!DOCTYPE HTML>
<html>

<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script>
$(document).ready(function() {    
  $(".trigger").click(function() {
    $(".menu").toggleClass("active"); 
  });
});

</script>

<style>
.absolute-center,
.menu,
.menu .btn .fa,
.menu .btn.trigger .line {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translateX(-50%) translateY(-50%);
  -ms-transform: translateX(-50%) translateY(-50%);
  transform: translateX(-50%) translateY(-50%);
}

.menu {
  width: 5em;
  height: 5em;
}

.menu .btn {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border-radius: 50%;
  background: rgba(255, 015, 255, 0.15);
  opacity: 0;
  z-index: -10;
  cursor: pointer;
  -webkit-transition: opacity 1s, z-index 0.3s, -webkit-transform 1s;
  transition: opacity 1s, z-index 0.3s, transform 1s;
  -webkit-transform: translateX(0);
  -ms-transform: translateX(0);
  transform: translateX(0);
}

.menu .btn .fa {
  font-size: 3em;
  -webkit-transition: color 0.3s;
  transition: color 0.3s;
}

.menu .btn:hover .fa { color: rgba(255, 255, 255, 0.7); }

.menu .btn.trigger {
  opacity: 1;
  z-index: 100;
  cursor: pointer;
  -webkit-transition: -webkit-transform 0.3s;
  transition: transform 0.3s;
}

.menu .btn.trigger:hover {
  -webkit-transform: scale(1.2);
  -ms-transform: scale(1.2);
  transform: scale(1.2);
}

.menu .btn.trigger:hover .line { background-color: rgba(255, 255, 255, 0.7); }

.menu .btn.trigger:hover .line:before,
.menu .btn.trigger:hover .line:after { background-color: rgba(255, f15, 255, 0.7); }

.menu .btn.trigger .line {
  width: 60%;
  height: 6px;
  background: #000;
  border-radius: 6px;
  -webkit-transition: background-color 0.3s, height 0.3s, top 0.3s;
  transition: background-color 0.3s, height 0.3s, top 0.3s;
}

.menu .btn.trigger .line:before,
.menu .btn.trigger .line:after {
  content: "";
  display: block;
  position: absolute;
  left: 0;
  width: 100%;
  height: 6px;
  background: #000;
  border-radius: 6px;
  -webkit-transition: background-color 0.3s, -webkit-transform 0.3s;
  transition: background-color 0.3s, transform 0.3s;
}

.menu .btn.trigger .line:before {
  top: -12px;
  -webkit-transform-origin: 15% 100%;
  -ms-transform-origin: 15% 100%;
  transform-origin: 15% 100%;
}

.menu .btn.trigger .line:after {
  top: 12px;
  -webkit-transform-origin: 25% 30%;
  -ms-transform-origin: 25% 30%;
  transform-origin: 25% 30%;
}

.menu .rotater {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  -webkit-transform-origin: 50% 50%;
  -ms-transform-origin: 50% 50%;
  transform-origin: 50% 50%;
}

.menu.active .btn-icon {
  opacity: 1;
  z-index: 50;
}

.menu.active .trigger .line {
  height: 0px;
  top: 45%;
}

.menu.active .trigger .line:before {
  -webkit-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  transform: rotate(45deg);
  width: 110%;
}

.menu.active .trigger .line:after {
  -webkit-transform: rotate(-45deg);
  -ms-transform: rotate(-45deg);
  transform: rotate(-45deg);
  width: 110%;
}

/* horrible things are happening here
for some reason nth-child(1) is always busy and elements starting from 2 */

.rotater:nth-child(1) {
  -webkit-transform: rotate(-22.5deg);
  -ms-transform: rotate(-22.5deg);
  transform: rotate(-22.5deg);
}

.menu.active .rotater:nth-child(1) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(22.5deg);
  -ms-transform: translateX(-10em) rotate(22.5deg);
  transform: translateX(-10em) rotate(22.5deg);
}

.rotater:nth-child(2) {
  -webkit-transform: rotate(22.5deg);
  -ms-transform: rotate(22.5deg);
  transform: rotate(22.5deg);
}

.menu.active .rotater:nth-child(2) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(-22.5deg);
  -ms-transform: translateX(-10em) rotate(-22.5deg);
  transform: translateX(-10em) rotate(-22.5deg);
}

.rotater:nth-child(3) {
  -webkit-transform: rotate(67.5deg);
  -ms-transform: rotate(67.5deg);
  transform: rotate(67.5deg);
}

.menu.active .rotater:nth-child(3) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(-67.5deg);
  -ms-transform: translateX(-10em) rotate(-67.5deg);
  transform: translateX(-10em) rotate(-67.5deg);
}

.rotater:nth-child(4) {
  -webkit-transform: rotate(112.5deg);
  -ms-transform: rotate(112.5deg);
  transform: rotate(112.5deg);
}

.menu.active .rotater:nth-child(4) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(-112.5deg);
  -ms-transform: translateX(-10em) rotate(-112.5deg);
  transform: translateX(-10em) rotate(-112.5deg);
}

.rotater:nth-child(5) {
  -webkit-transform: rotate(157.5deg);
  -ms-transform: rotate(157.5deg);
  transform: rotate(157.5deg);
}

.menu.active .rotater:nth-child(5) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(-157.5deg);
  -ms-transform: translateX(-10em) rotate(-157.5deg);
  transform: translateX(-10em) rotate(-157.5deg);
}

.rotater:nth-child(6) {
  -webkit-transform: rotate(202.5deg);
  -ms-transform: rotate(202.5deg);
  transform: rotate(202.5deg);
}

.menu.active .rotater:nth-child(6) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(-202.5deg);
  -ms-transform: translateX(-10em) rotate(-202.5deg);
  transform: translateX(-10em) rotate(-202.5deg);
}

.rotater:nth-child(7) {
  -webkit-transform: rotate(247.5deg);
  -ms-transform: rotate(247.5deg);
  transform: rotate(247.5deg);
}

.menu.active .rotater:nth-child(7) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(-247.5deg);
  -ms-transform: translateX(-10em) rotate(-247.5deg);
  transform: translateX(-10em) rotate(-247.5deg);
}

.rotater:nth-child(8) {
  -webkit-transform: rotate(292.5deg);
  -ms-transform: rotate(292.5deg);
  transform: rotate(292.5deg);
}

.menu.active .rotater:nth-child(8) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(-292.5deg);
  -ms-transform: translateX(-10em) rotate(-292.5deg);
  transform: translateX(-10em) rotate(-292.5deg);
}

.rotater:nth-child(9) {
  -webkit-transform: rotate(337.5deg);
  -ms-transform: rotate(337.5deg);
  transform: rotate(337.5deg);
}

.menu.active .rotater:nth-child(9) .btn-icon {
  -webkit-transform: translateX(-10em) rotate(-337.5deg);
  -ms-transform: translateX(-10em) rotate(-337.5deg);
  transform: translateX(-10em) rotate(-337.5deg);
}

.glyphicon {
    font-size: 40px;
}

body  {
    background-image: url("https://s-media-cache-ak0.pinimg.com/originals/3b/2e/83/3b2e836bf5c14703c4921a1059ca7c08.jpg");
     background-repeat: no-repeat;
    
}


</style>





</head>

<body>

                       


<link href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<div class="menu">
  <div class="btn trigger">
    <span class="line"></span>
  </div>
  <div class="icons">
    <div class="rotater">
       <div class="btn btn-icon" >
       <a href="http://localhost:3000/proteinC"> <i class="glyphicon glyphicon-heart-empty" ></i></a>

        </div>

    
    </div>
    <div class="rotater">
      <div class="btn btn-icon" >
       <a href="https://www.facebook.com/"><i class="glyphicon glyphicon-star" aria-hidden="true"></i>  </a>
       
       
    
      </div>
    </div>
    <div class="rotater">
      <div class="btn btn-icon">
<<<<<<< HEAD
       <a <%= link_to 'About Us', home1_about_url %><i class="fa fa-copyright" aria-hidden="true"></i></a>
=======
        <a href="http://localhost:3000/home1/about/"><i class="fa fa-copyright" aria-hidden="true"></i></a>
>>>>>>> 70be4acc630098f654cde83091a2479e909d57e8

      </div>
    </div>
    <div class="rotater">
      <div class="btn btn-icon" >

<<<<<<< HEAD
      <a <%= link_to 'Food History', customersps_path %><i class="fa fa-history" aria-hidden="true"></i></a>
=======
       <a href="http://localhost:3000/customersps"><i class="fa fa-history" aria-hidden="true"></i></a>
>>>>>>> 70be4acc630098f654cde83091a2479e909d57e8

      </div>
    </div>
    <div class="rotater">
      <div class="btn btn-icon">
<<<<<<< HEAD
       <a <%= link_to 'Contact', home1_contactUs_url %><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i></a>
=======
       <a href="http://localhost:3000/home1/contactUs"><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i></a>
>>>>>>> 70be4acc630098f654cde83091a2479e909d57e8
      </div>
    </div>
    <div class="rotater">
      <div class="btn btn-icon">
      <a href="http://localhost:3000/fat"><i class="fa fa-copyright" aria-hidden="true"></i></a>
      </div>
    </div>
    <div class="rotater">
      <div class="btn btn-icon">
          <a href="http://localhost:3000/homevd/index"><i class="fa fa-table" aria-hidden="true"></i></a>
      </div>
    </div>
    <div class="rotater">
      <div class="btn btn-icon">
<<<<<<< HEAD
    <a <%= link_to 'Graphs Testing', graphs_url %>    <i class="fa fa-line-chart" aria-hidden="true"></i> </a>
=======
  <a href="http://localhost:3000/graphs/"><i class="fa fa-line-chart" aria-hidden="true"></i> </a>
>>>>>>> 70be4acc630098f654cde83091a2479e909d57e8
      </div>
    </div>
  </div>
</div>

</body>

</html>