config/routes.rb
Rails.application.routes.draw do
  
  resources :donations
  get 'donation/index'
  resources :reviews
  get 'homevd/index'

  get 'home/index'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'products/index'

  get 'payments/searchingName'

  post 'validate3',  :controller=>'payments', :action=>'results' 

  resources :foods

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

resources :payments, only: [:index, :new, :create]
  get 'payments/index'

  get 'payments/new'

  get 'payments/create'

  resources :needs
  resources :customersps do
      resources :foodsps
end

get '/fat' =>'fatintake#checkFatIntakeSP'
post '/validate1' =>'fatintake#isFatCal'

  resources :shakes
  resources :profiles
  resources :analytics
  resources :customers
  get 'home2/index'

  get 'home1/index'

  get 'home1/about'
  
  get '/graphs' =>'analytics#graphs'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  
  get '/proteinC' =>'analytics#proteinCalc'
  
  
  post '/validate', :controller=>'analytics', :action=>'proteinCounter'

  get 'home1/contactUs'

  get 'home1/findUs'

  devise_for :users

  root :to => 'home1#index'
  
  get 'home/index'
  

end

app/models/customersp.rb
class Customersp < ActiveRecord::Base
	has_many :foodsps

validates :namesp, :surnamesp, :emailsp, presence: true
# validate that the phone number only contains digits
# tests if the value of the phone matches
# the regular expression given via with:
validates :phonesp, format: { with: /\A[0-9]+\z/,
message: "accepts digits only!" }
# we have to add the error so that the record becomes invalid
# when the value of the attribute does not match the
# regular expression
validates_each :namesp, :surnamesp do |record, attr, value|
record.errors.add(attr, 'must contain only letters!') if
value =~ /[^\A[a-zA-Z]+\z]/
end


end

app/controllers/customersps_controller.rb
require 'sp_logger'
class CustomerspsController < ApplicationController
  before_action :set_customersp, only: [:show, :edit, :update, :destroy]

  # GET /customersps
  # GET /customersps.json
  def index
    @customersps = Customersp.all
  end

  # GET /customersps/1
  # GET /customersps/1.json
  def show
  end



  # GET /customersps/new
  def new
    @customersp = Customersp.new
  end

  # GET /customersps/1/edit
  def edit
  end

  # POST /customersps
  # POST /customersps.json
  def create
    @customersp = Customersp.new(customersp_params)

    # retrieve the instance/object of the MyLogger class
logger = SpLogger.instance
logger.logInformation("A new Customer requested: " + @customersp.namesp + @customersp.surnamesp + @customersp.emailsp + @customersp.phonesp)

    respond_to do |format|
      if @customersp.save
        format.html { redirect_to @customersp, notice: 'Customersp was successfully created.' }
        format.json { render :show, status: :created, location: @customersp }
      else
        format.html { render :new }
        format.json { render json: @customersp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customersps/1
  # PATCH/PUT /customersps/1.json
  def update
    respond_to do |format|
      if @customersp.update(customersp_params)
        format.html { redirect_to @customersp, notice: 'Customersp was successfully updated.' }
        format.json { render :show, status: :ok, location: @customersp }
      else
        format.html { render :edit }
        format.json { render json: @customersp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customersps/1
  # DELETE /customersps/1.json
  def destroy
    @customersp.destroy
    respond_to do |format|
      format.html { redirect_to customersps_url, notice: 'Customersp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customersp
      @customersp = Customersp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customersp_params
      params.require(:customersp).permit(:namesp, :surnamesp, :emailsp, :phonesp)
    end
end

app/helpers/customersps_helper.rb
module CustomerspsHelper
end

app/views/customersps/_form.html.erb
<%= form_for(@customersp) do |f| %>
  <% if @customersp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customersp.errors.count, "error") %> prohibited this customersp from being saved:</h2>

      <ul>
      <% @customersp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name%><br>
    <%= f.text_field :namesp %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surnamesp %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :emailsp %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phonesp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customersps/edit.html.erb
<h1>Edit your Details</h1>

<%= render 'form' %>

<%= link_to 'Show', @customersp %> |
<%= link_to 'Back', customersps_path %>

app/views/customersps/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<head>
<style>
body {
  
    background-height:auto;
    background-size: cover;
   
    
    background-image: url("http://www.freeimageslive.com/galleries/food/misc/pics/fridgeblured1641.jpg");
    background-repeat: no-repeat;

}


</style>
</head>



<p id="notice"><%= notice %></p>

<h1>Welcome to FridgeHistory </h1>



<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customersps.each do |customersp| %>
      <tr>
        <td><%= customersp.namesp %></td>
        <td><%= customersp.surnamesp %></td>
        <td><%= customersp.emailsp %></td>
        <td><%= customersp.phonesp %></td>
        <td><h1><%= link_to 'View Profile', customersp %></h1></td>
        <td><h3><%= link_to 'Edit ', edit_customersp_path(customersp) %></h3></td>
        <td><%= link_to 'Remove ', customersp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


 <%= link_to 'New Customer', new_customersp_path %>

app/views/customersps/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customersps_path %>

app/views/customersps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><h3>Name:</h3></strong>
  <h4><%= @customersp.namesp %></h4>
</p>

<p>
  <strong><h3>Surname:</h3></strong>
  <h4><%= @customersp.surnamesp %></h4>
</p>

<p>
  <strong><h3>Email:</h3></strong>
  <h4><%= @customersp.emailsp %></h4>
</p>

<p>
  <strong><h3>Phone:</h3></strong>
  <h4><%= @customersp.phonesp %></h4>
</p>

<!-- Display the foodsp of a customersp -->
<h2>Foodsps</h2>
<% @customersp.foodsps.each do |foodsp| %>
<p>
<b>Product:</b>
<%= foodsp.productsp %>
<b>Pricesp:</b>
<%= foodsp.pricesp %>
<b>Expirysp:</b>
<%= foodsp.expirysp %>
<b>Caloriessp:</b>
<%= foodsp.caloriessp %>
<b>Proteinssp:</b>
<%= foodsp.proteinssp %>
<b>Sugarsp:</b>
<%= foodsp.sugarsp %>
<b>Fatsp:</b>
<%= foodsp.fatsp %>
</p>
<% end %>

<%= link_to 'Edit', edit_customersp_path(@customersp) %> |
<%= link_to 'Back', customersps_path %> |
<%= link_to 'Show Food', customersp_foodsps_path(@customersp) %>