config/routes.rb
Rails.application.routes.draw do
  
  resources :donations
  get 'donation/index'
  resources :reviews
  get 'homevd/index'

  get 'home/index'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'products/index'

  get 'payments/searchingName'

  post 'validate3',  :controller=>'payments', :action=>'results' 

  resources :foods

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

resources :payments, only: [:index, :new, :create]
  get 'payments/index'

  get 'payments/new'

  get 'payments/create'

  resources :needs
  resources :customersps do
      resources :foodsps
end

get '/fat' =>'fatintake#checkFatIntakeSP'
post '/validate1' =>'fatintake#isFatCal'

  resources :shakes
  resources :profiles
  resources :analytics
  resources :customers
  get 'home2/index'

  get 'home1/index'

  get 'home1/about'
  
  get '/graphs' =>'analytics#graphs'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  
  get '/proteinC' =>'analytics#proteinCalc'
  
  
  post '/validate', :controller=>'analytics', :action=>'proteinCounter'

  get 'home1/contactUs'

  get 'home1/findUs'

  devise_for :users

  root :to => 'home1#index'
  
  get 'home/index'
  

end

app/models/need.rb
class Need < ActiveRecord::Base

validates :firstname, :description, presence: true

validates :lastname, :manufacturer, :color, format: { with: /\A[0-9]+\z/,
message: "accepts digits only!" }


validates_each :firstname, :description do |record, attr, value|
record.errors.add(attr, 'must contain only letters!') if
value =~ /[^\A[a-zA-Z]+\z]/
end

end

app/controllers/needs_controller.rb
require 'sp_logger'
require 'need_decorator'
class NeedsController < ApplicationController
  before_action :set_need, only: [:show, :edit, :update, :destroy]

  # GET /needs
  # GET /needs.json
  def index
    @needs = Need.all
  end

  # GET /needs/1
  # GET /needs/1.json
  def show
  end

  # GET /needs/new
  def new
    @need = Need.new
  end

  # GET /needs/1/edit
  def edit
  end

  # POST /needs
  # POST /needs.json
  def create


@need = Need.new()
@need.firstname = params[:need][:firstname]
@need.lastname = params[:need][:lastname]
@need.color = params[:need][:color]
@need.manufacturer = params[:need][:manufacturer]
# create an instance/object of a BasicCar
myNeed = BasicNeed.new(2000, @need.manufacturer, @need.color)
# add the extra features to the new need
if params[:need][:milk].to_s.length > 0 then
myNeed = MilkDecorator.new(myNeed)
end
if params[:need][:egg].to_s.length > 0 then
myNeed = EggDecorator.new(myNeed)
end
if params[:need][:bread].to_s.length > 0 then
myNeed = BreadDecorator.new(myNeed)
end
## populate the cost and the description details
@need.cost = myNeed.cost
@need.description = myNeed.details

# Singleton Logg
logger = SpLogger.instance
logger.logInformation(" A new Basic Need is added:" + @need.description)

respond_to do |format|
if @need.save
format.html { redirect_to @need, notice: 'need was successfully created.'}
format.json { render :show, status: :created, location: @need }
else
format.html { render :new }

format.json { render json: @need.errors, status: :unprocessable_entity }
end
end
end

  # PATCH/PUT /needs/1
  # PATCH/PUT /needs/1.json
  def update
    # update the instance variables with the information
# user provided in the form
# retrieve each value from the params hash
@need.firstname = params[:need][:firstname]
@need.lastname = params[:need][:lastname]
@need.color = params[:need][:color]
@need.manufacturer = params[:need][:manufacturer]
# create an instance/object of a BasicNeed
# here I hard-code the cost of a need,
# namely all my basic cars are going to cost 15000
myNeed = BasicNeed.new(20, @need.manufacturer, @need.color)
# add the extra features to the myNeed object if the user selected them
# we use an implementation of the decorator pattern
# to dynamically provide the extra features to a need
# each of the check-boxex the user checks is implemented as a decoration
if params[:need][:milk].to_s.length > 0 then
myNeed = MilkDecorator.new(myNeed)
end
if params[:need][:egg].to_s.length > 0 then
myNeed = EggDecorator.new(myNeed)
end
if params[:need][:bread].to_s.length > 0 then
myNeed = BreadDecorator.new(myNeed)
end
## update the cost and the description details
@need.cost = myNeed.cost
@need.description = myNeed.details

# build a hash with the updated information of the car
updated_information = {
"firstname" => @need.firstname,
"lastname" => @need.lastname,
"manufacturer" => @need.manufacturer,
"cost" => @need.cost,
"description" => @need.description,
"color" => @need.color
}
respond_to do |format|
# call the method update() of the ActiveRecord instance
# to update the car with the new information
# note that the method update() of the ActiveRecord receives
# the hash we created above
if @need.update(updated_information)
format.html { redirect_to @need, notice: 'need was successfully updated.' }
format.json { render :show, status: :ok, location: @need }
else
format.html { render :edit }
format.json { render json: @need.errors, status: :unprocessable_entity }
end
end
end

  # DELETE /needs/1
  # DELETE /needs/1.json
  def destroy
    @need.destroy
    respond_to do |format|
      format.html { redirect_to needs_url, notice: 'Need was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_need
      @need = Need.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def need_params
      params.require(:need).permit(:firstname, :lastname, :manufacturer, :cost, :description, :color)
    end
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/views/needs/_form.html.erb
<%= form_for(@need) do |f| %>
  <% if @need.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@need.errors.count, "error") %> prohibited this need from being saved:</h2>

      <ul>
      <% @need.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :sugar %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :fat %><br>
    <%= f.text_field :color %>
  </div>

<div class="field">
MILK:
<%= check_box_tag 'need[milk]', 'milk' %>
</div>
<div class="field">
EGG:
<%= check_box_tag 'need[egg]', 'egg' %>
</div>
<div class="field">
BREAD:
<%= check_box_tag 'need[bread]', 'bread' %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/needs/edit.html.erb
<h1>Editing Need</h1>

<%= render 'form' %>

<%= link_to 'Show', @need %> |
<%= link_to 'Back', needs_path %>

app/views/needs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Needs</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Calories</th>
      <th>Sugar</th>
      <th>Price</th>
      <th>Description</th>
      <th>Fats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @needs.each do |need| %>
      <tr>
        <td><%= need.firstname %></td>
        <td><%= need.lastname %></td>
        <td><%= need.manufacturer %></td>
        <td><%= need.cost %></td>
        <td><%= need.description %></td>
        <td><%= need.color %></td>
        <td><%= link_to 'Show', need %></td>
        <td><%= link_to 'Edit', edit_need_path(need) %></td>
        <td><%= link_to 'Destroy', need, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<h3><%= link_to 'Add New Need', new_need_path %></h3>

<h3> <%= link_to 'Back to Profile', customersps_path %></h3>

app/views/needs/new.html.erb
<h1>New Need</h1>

<%= render 'form' %>

<%= link_to 'Back', needs_path %>

app/views/needs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @need.firstname %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @need.lastname %>
</p>

<p>
  <strong>Sugar:</strong>
  <%= @need.manufacturer %>
</p>

<p>
  <strong>Price:</strong>
  <%= @need.cost %>
</p>

<p>
  <strong>Description:</strong>
  <%= @need.description %>
</p>

<p>
  <strong>Fat:</strong>
  <%= @need.color %>
</p>

<%= link_to 'Edit', edit_need_path(@need) %> |
<%= link_to 'Back', needs_path %>