config/routes.rb
Rails.application.routes.draw do
  
  resources :donations
  get 'donation/index'
  resources :reviews
  get 'homevd/index'

  get 'home/index'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'products/index'

  get 'payments/searchingName'

  post 'validate3',  :controller=>'payments', :action=>'results' 

  resources :foods

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

resources :payments, only: [:index, :new, :create]
  get 'payments/index'

  get 'payments/new'

  get 'payments/create'

  resources :needs
  resources :customersps do
      resources :foodsps
end

get '/fat' =>'fatintake#checkFatIntakeSP'
post '/validate1' =>'fatintake#isFatCal'

  resources :shakes
  resources :profiles
  resources :analytics
  resources :customers
  get 'home2/index'

  get 'home1/index'

  get 'home1/about'
  
  get '/graphs' =>'analytics#graphs'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  
  get '/proteinC' =>'analytics#proteinCalc'
  
  
  post '/validate', :controller=>'analytics', :action=>'proteinCounter'

  get 'home1/contactUs'

  get 'home1/findUs'

  devise_for :users

  root :to => 'home1#index'
  
  get 'home/index'
  

end

app/models/donation.rb
class Donation < ActiveRecord::Base
    
    has_many :orders
validates :firstname, :lastname, presence: true
end

app/controllers/donations_controller.rb
require 'donation_decorator_example'
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
def create
  @donation = Donation.new()
  @donation.firstname = params[:donation][:firstname]
  @donation.lastname = params[:donation][:lastname]
  @donation.cost = params[:donation][:cost]
  # create an instance/object of a BasicCar
  myDonation = BasicDonation.new(@donation.cost)
  # add the extra features to the new car
  if params[:donation][:SaveChild].to_s.length > 0 then
    myDonation = ChildDecorator.new(myDonation)
  end
  if params[:donation][:HelpOldPeople].to_s.length > 0 then
    myDonation = OldDecorator.new(myDonation)
  end
## populate the cost and the description details
    @donation.cost = myDonation.cost
    @donation.description = myDonation.details
    
  

  respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    
    # update the instance variables with the information
# user provided in the form
# retrieve each value from the params hash
@donation.firstname = params[:donation][:firstname]
@donation.lastname = params[:donation][:lastname]
@donation.cost = params[:donation][:cost]
# create an instance/object of a BasicCar
# here I hard-code the cost of a car,
# namely all my basic cars are going to cost 15000
myDonation = BasicDonation.new(15)
# add the extra features to the myCar object if the user selected them
# we use an implementation of the decorator pattern
# to dynamically provide the extra features to a car
# each of the check-boxex the user checks is implemented as a decoration
if params[:donation][:SvaeChild].to_s.length > 0 then
myDonation = ChildDecorator.new(myDonation)
end
if params[:donation][:HelpOldPeople].to_s.length > 0 then
myDonation = OldDecorator.new(myDonation)
end

## update the cost and the description details
@donation.cost = myDonation.cost
@donation.description = myDonation.details

# build a hash with the updated information of the car
updated_information = {
"firstname" => @donation.firstname,
"lastname" => @donation.lastname,

"cost" => @donation.cost,


}
  respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:firstname, :lastname, :cost, :description)
    end
  end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
<div class="field">
Save Child:
<%= check_box_tag 'donation[SaveChild]', 'SaveChild' %>
</div>
<div class="field">
Help Old People:
<%= check_box_tag 'donation[HelpOldPeople]', 'HelpOldPeople' %>
</div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<div class="border-form-div"><h1>Editing Donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>
</div>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Donations</h1>

<table class="table table-hover">

  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Cost</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.firstname %></td>
        <td><%= donation.lastname %></td>
        <td><%= donation.cost %></td>
        <td><%= donation.description %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<div class="border-form-div"><h1>New Donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>
</div

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @donation.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @donation.lastname %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @donation.cost %>
</p>

<p>
  <strong>Description:</strong>
  <%= @donation.description %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>